'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { site } from './site';
function track(name:string, params:Record<string,string>={}) { window.dispatchEvent(new CustomEvent('vesspektr:conversion', {detail:{event:name,...params}})); const w=window as Window & {dataLayer?:Record<string,string>[]}; w.dataLayer?.push({event:name,...params}); }
export function Tracking(){useEffect(()=>{const click=(e:MouseEvent)=>{const a=(e.target as Element).closest<HTMLElement>('[data-track]');if(a?.dataset.track)track(a.dataset.track);};document.addEventListener('click',click);return()=>document.removeEventListener('click',click);},[]);return null;}
export function Header(){const [open,setOpen]=useState(false);return <header className="header"><div className="header-inner"><a className="brand" href="#" onClick={()=>setOpen(false)}>ВЕСЬ СПЕКТР<span>ЛЕСТНИЦЫ И ОГРАЖДЕНИЯ</span></a><nav className={open?'nav open':'nav'} id="navigation" aria-label="Главная навигация">{[['#types','Конструкции'],['#projects','Лестницы'],['#process','Этапы'],['#contacts','Контакты']].map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="header-phone" href={`tel:${site.phone}`} data-track="phone_click">{site.phoneDisplay}</a><button className="menu-button" aria-expanded={open} aria-controls="navigation" aria-label={open?'Закрыть меню':'Открыть меню'} onClick={()=>setOpen(!open)}>{open?'✕':'☰'}</button></div></header>}
const photos=[{src:'/images/project-1.jpg',title:'Геометрия поворота',alt:'Бетонная лестница с забежными ступенями',tag:'ЗАБЕЖНЫЕ СТУПЕНИ'},{src:'/images/project-2.jpg',title:'Основа для интерьера',alt:'Монолитная лестница в частном доме',tag:'В ЧАСТНЫЙ ДОМ'},{src:'/images/project-3.jpg',title:'Пластика бетона',alt:'Винтовая бетонная лестница',tag:'ВИНТОВАЯ ФОРМА'}];
export function Gallery(){const dialog=useRef<HTMLDialogElement>(null);const [active,setActive]=useState(0);return <><div className="gallery">{photos.map((p,i)=><button key={p.src} className="project" onClick={()=>{setActive(i);dialog.current?.showModal();}} aria-label={`Увеличить фото: ${p.alt}`}><div className="project-image"><Image src={p.src} alt={p.alt} fill sizes="(max-width: 650px) 100vw, 33vw"/><span className="zoom" aria-hidden="true">↗</span></div><div className="project-caption"><span>{p.tag}</span><h3>{p.title}</h3></div></button>)}</div><dialog ref={dialog} className="lightbox" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button className="close" onClick={()=>dialog.current?.close()} aria-label="Закрыть фотографию">✕</button><div className="lightbox-image"><Image src={photos[active].src} alt={photos[active].alt} fill sizes="90vw"/></div><p>{photos[active].alt}</p><div className="lightbox-controls"><button onClick={()=>setActive((active+2)%3)} aria-label="Предыдущее фото">←</button><span>{active+1} / {photos.length}</span><button onClick={()=>setActive((active+1)%3)} aria-label="Следующее фото">→</button></div></dialog></>}
export function LeadForm({directSubmit}:{directSubmit:boolean}){
 const [kind,setKind]=useState('Нужна помощь');const [finish,setFinish]=useState('Пока не знаю');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [sent,setSent]=useState(false);const [emailHref,setEmailHref]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setEmailHref('');const form=new FormData(e.currentTarget);const phone=String(form.get('phone')||'');if(!/^[+\d\s()\-]{7,25}$/.test(phone)||phone.replace(/\D/g,'').length<7){setError('Проверьте номер телефона: укажите код страны и номер.');return;}const data={name:String(form.get('name')||''),phone,city:String(form.get('city')||''),comment:String(form.get('comment')||''),website:String(form.get('website')||''),consent:form.get('consent')==='on',kind,finish,attribution:Object.fromEntries([...new URLSearchParams(location.search)].filter(([k])=>['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','yclid'].includes(k)).map(([k,v])=>[k,v.slice(0,200)]))};
 if(!directSubmit){const body=`Здравствуйте! Прошу рассчитать бетонную лестницу.\n\nКонструкция: ${kind}\nОтделка: ${finish}\nИмя: ${data.name}\nТелефон: ${phone}\nНаселённый пункт: ${data.city}\nКомментарий: ${data.comment}`;setEmailHref(`mailto:${site.email}?subject=${encodeURIComponent('Расчёт бетонной лестницы')}&body=${encodeURIComponent(body)}`);track('estimate_prepared');return;}
 setBusy(true);try{const response=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не удалось отправить запрос.');setSent(true);track('lead_success');}catch(err){setError(err instanceof Error?err.message:'Не удалось отправить запрос. Позвоните нам.');}finally{setBusy(false);}}
 if(sent)return <div className="lead-card success" role="status"><span className="success-mark">✓</span><h3>Спасибо за запрос!</h3><p>Ваши данные переданы специалисту. Мы свяжемся с вами, чтобы обсудить лестницу.</p><button className="button dark" onClick={()=>setSent(false)}>Новый запрос</button></div>;
 return <form className="lead-card" onSubmit={submit} onChange={()=>setEmailHref('')}><div className="form-head"><h3>Расскажите о лестнице</h3><span>~ 1 минута</span></div><fieldset><legend>01. Какая конструкция вам нужна?</legend><div className="choices">{['Прямая','Г-образная','П-образная','Винтовая','Нужна помощь'].map(x=><label key={x} className={kind===x?'choice selected':'choice'}><input type="radio" name="kind" value={x} checked={kind===x} onChange={()=>setKind(x)}/>{x}</label>)}</div></fieldset><label className="field">02. Отделка<select value={finish} onChange={e=>setFinish(e.target.value)}>{['Пока не знаю','Без отделки','Дерево','Плитка','Камень'].map(x=><option key={x}>{x}</option>)}</select></label><div className="form-grid"><label className="field">Ваше имя<input name="name" autoComplete="given-name" placeholder="Как к вам обращаться" maxLength={80}/></label><label className="field">Телефон *<input name="phone" type="tel" autoComplete="tel" placeholder="+375 (__) ___-__-__" required maxLength={25}/></label></div><label className="field">Где находится объект?<input name="city" autoComplete="address-level2" placeholder="Город или населённый пункт" maxLength={100}/></label><label className="field">Размеры и пожелания<textarea name="comment" placeholder="Высота этажа, размер проёма или ваш вопрос" rows={3} maxLength={1500}/></label><div className="honeypot" aria-hidden="true"><label>Ваш сайт<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><input type="checkbox" name="consent" required/><span>Разрешаю использовать указанные данные, чтобы связаться со мной по поводу расчёта лестницы.</span></label><p className="privacy-note">Получатель — «Весь Спектр». По вопросам использования данных: <a href={`mailto:${site.email}`}>{site.email}</a>.</p><button className="button lime submit" type="submit" disabled={busy}>{busy?'Отправляем…':directSubmit?'Запросить расчёт':'Подготовить запрос'}<span aria-hidden="true">↗</span></button>{!directSubmit&&<p className="form-note">Подготовим письмо с вашими параметрами. Вы отправите его из своей почты.</p>}{error&&<p className="form-error" role="alert">{error} Можно связаться напрямую: <a href={`tel:${site.phone}`}>{site.phoneDisplay}</a>.</p>}{emailHref&&<div className="email-ready" role="status"><strong>Запрос подготовлен</strong><p>Откройте письмо, при необходимости прикрепите план и нажмите «Отправить» в почтовом приложении.</p><a className="button dark" href={emailHref} onClick={()=>track('email_request_click')}>Открыть письмо ↗</a><p>Нет почтового приложения? Напишите на <a href={`mailto:${site.email}`}>{site.email}</a> или позвоните.</p></div>}</form>;
}
